// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smhsisabarlzqwwmwvxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaHNpc2FiYXJsenF3d213dnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTE5NDcsImV4cCI6MjA2MjcyNzk0N30.Nal5gJoZvlUXDiMkN4OSzJYD-dAZxDYWth8XSfMeEA0";

// Create the Supabase client
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";